/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package complejo;
import java.awt.*;
import javax.swing.*;
import complejo.Calculadora;
public class Plano extends javax.swing.JPanel {
  private Complejo[] c1;
  
    public Plano(Complejo[] c1) {
        this.c1=c1;
        init();
    }
    public void init(){
        this.setBorder(BorderFactory.createLineBorder(Color.black));
    }
    
    @Override
    public void paintComponent(Graphics g){
        
        super.paintComponent(g);
        
        g.setColor(Color.blue);
        g.drawLine(0, this.getHeight()/2,this.getWidth(), this.getHeight()/2);
        g.drawLine(this.getWidth()/2,0,this.getWidth()/2, this.getHeight());
        for(Complejo c:c1){
            this.paintFunc(g,c);
        }
        
    }
    public void paintFunc(Graphics g, Complejo caca){
        //--
        Graphics2D g2 = (Graphics2D) g;
        g2.setStroke(new BasicStroke(3));
        g2.setColor(Color.black);
        g2.drawLine((this.getWidth()/2),this.getHeight()/2,(this.getWidth()/2)+((int)caca.getParteReal())*25,(this.getHeight()/2)-((int)caca.getParteImaginaria())*25);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
//